---

- name: Check if repo exists
  stat:
    path: "/home/{{ username }}/btcpool-docker-compose"
  register: btcpool_git

- name: Clone btcpool-docker-compose repo
  git:
    repo: "https://github.com/insight-stratum/btcpool-docker-compose"
    dest: "/home/{{ username }}/btcpool"
    version: "0.0.1"
  become_user: "{{ username }}"
  when: not btcpool_git.stat.exists

- name: Start node application via docker-compose
  shell: # noqa 301 305
    cmd: "STACK={{ stack_type }} make start > startup.log"
    chdir: "/home/{{ username }}/btcpool"
  async: 1500
  poll: 10