---

- name: Check if repo exists
  stat:
    path: "/home/{{ username }}/btcpool-docker-compose"
  register: btcpool_git

- name: Clone btcpool-docker-compose repo
  git:
    repo: "https://github.com/insight-stratum/btcpool-docker-compose"
    dest: "/home/{{ username }}/btcpool"
  become_user: "{{ username }}"
  when: btcpool_git.stat.exists == false

- name: Start node application via docker-compose
  shell:
    cmd: make start
    chdir: "/home/{{ username }}/btcpool"
