---

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Install required packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3
      - python3-dev
      - python3-pip
      - docker-ce
      - curl
      - jq

- name: Add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Install pip3 packages
  pip:
    name: "{{ pippkgs }}"
    executable: pip3
    state: present
  vars:
    pippkgs:
      - pip
      - docker
      - docker-compose
