---

- name: Run certbot for SSL
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_create_if_missing: true
    certbot_admin_email: "{{ certbot_admin_email }}"
    certbot_certs:
      - domains:
          - "{{ fqdn }}"
    certbot_create_standalone_stop_services: []

- name: Copy over nginx conf for SSL
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Copy over btcpool nginx conf for SSL
  template:
    src: btcpool.conf.j2
    dest: /etc/nginx/sites-enabled/btcpool.conf
    mode: 0644
  notify:
    - restart nginx

- name: Create cert directory if it does not exist
  file:
    path: "/home/{{ username }}/btcpool/certs"
    state: directory
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ group_name }}"
  when: ssl_enable

- name: Move cert to certs
  command: cp /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem /home/{{ username }}/btcpool/certs/fullchain.pem
  when: ssl_enable

- name: Move key to certs
  command: cp /etc/letsencrypt/live/{{ fqdn }}/privkey.pem /home/{{ username }}/btcpool/certs/privkey.pem
  when: ssl_enable

